[package]
name = "rust-keyvault"
version = "0.1.0"
edition = "2024"

[dependencies]
zeroize = { version = "1.7", features = ["derive"] }
subtle = "2.5"
thiserror = "1.0"
chacha20poly1305 = "0.10"
aes-gcm = "0.10"

rand_core = "0.6"
aead = "0.5"

rand_chacha = "0.3"

[dev-dependencies]
hex = "0.4"

[features]
default = []
#unstable = []
#hardware = []